console.log("FN",__dirname)
module.paths=(module.paths||[]).concat([__dirname+'/../../node_modules/'])
const postcss = require('postcss');
require("./fix-ugly-functions");
const imports = require('postcss-import');
const fixFontDeclarations = require('./fix-font-declarations');
const colorFunctions = require('./color-functions');
colorFunctions();
const gtkColorVariables = require('./color-variables');
const gtkPseudoClasses = require('./psuedo-classes');
const valueHook = require('./value-hook');

module.exports = postcss([imports(), fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, valueHook])
// Generated by CoffeeScript 2.2.3
/* (function() {
  var fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, imports, postcss, valueHook;

  postcss = require("postcss");

  require("./fix-ugly-functions");

  imports = require("postcss-import");

  fixFontDeclarations = require("./fix-font-declarations");

  gtkColorVariables = require("./color-variables");

  require("./color-functions");

  gtkPseudoClasses = require("./psuedo-classes");

  valueHook = require("./value-hook");

  module.exports = postcss([imports(), fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, valueHook]);

}).call(this); */
